version: '3.9'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /opt/app
    volumes:
      - .:/opt/app
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    working_dir: ${WORKING_DIR}/tests-bdd
    volumes:
      - ${WORKSPACE_MOUNT}:${WORKSPACE_PREFIX}
  chrome:
    image: selenium/standalone-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
