version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: node.Dockerfile
    init: true
    ports:
      - "9229:9229"
    image: gen-build-pipeline-node:2
    working_dir: ${WORKING_DIR}/cicd/gen-build-pipeline
    volumes:
      - ${WORKSPACE_MOUNT}:${WORKSPACE_PREFIX}
