version: "3.9"
services:
  jenkins:
    build:
      context: ./cicd/jenkins
    ports:
      - 8080:8080
    volumes:
      - .jenkins:/var/jenkins_home
      - .:/var/repo
  nexus:
    image: sonatype/nexus3:3.30.0
    ports:
      - 8081:8081
    volumes:
      - .nexus:/nexus-data
