version: "3.9"
services:
  jenkins:
    env_file: .env
    build:
      context: ./cicd/jenkins
    user: root
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/com.docker.cli:/usr/bin/com.docker.cli
      - /usr/bin/docker-compose:/usr/bin/docker-compose
      - .jenkins:/var/jenkins_home
    environment:
      AGENT_ROOT: /var/jenkins_home
      WORKSPACE_MOUNT: ${PWD}/.jenkins
  nexus:
    env_file: .env
    build:
      context: ./cicd/nexus
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
  nexus-provision:
    env_file: .env
    build:
      context: ./cicd/nexus-provision
    depends_on:
      - nexus
    restart: "no"
  smee-client:
    build:
      context: ./cicd/smee-client
    command: "-u https://smee.io/${SMEE_ID} -t http://jenkins:8080/github-webhook/"
volumes:
  nexus-data:
