version: "3.9"
services:
  ca:
    image: docker-repository-127-0-0-1.nip.io/step-ca:0.2.0-dev.0
    ports:
      - "8443:443"
    restart: always
    environment:
      VIRTUAL_HOST: ca-127-0-0-1.nip.io
      VIRTUAL_PROTO: https
  docker-repository-proxy:
    image: docker-repository-127-0-0-1.nip.io/docker-repository-proxy:0.2.0-dev.0
    environment:
      VIRTUAL_HOST: docker-repository-127-0-0-1.nip.io
      VIRTUAL_PORT: 8080
  jenkins:
    image: docker-repository-127-0-0-1.nip.io/jenkins:0.2.0-dev.0
    depends_on:
      - ca
    env_file: .env
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/com.docker.cli:/usr/bin/com.docker.cli
      - /usr/bin/docker-compose:/usr/bin/docker-compose
      - .jenkins:/var/jenkins_home
    environment:
      AGENT_ROOT: /var/jenkins_home
      STEP_CA_URL: https://ca
      STEP_FINGERPRINT: 84a033e84196f73bd593fad7a63e509e57fd982f02084359c4e8c5c864efc27d
      VIRTUAL_HOST: jenkins-127-0-0-1.nip.io
      VIRTUAL_PORT: 8080
      WORKSPACE_MOUNT: ${PWD}/.jenkins
    links:
      - "ingress:docker-repository-127-0-0-1.nip.io"
      - "ingress:nexus-127-0-0-1.nip.io"
  ingress:
    image: docker-repository-127-0-0-1.nip.io/ingress:0.2.0-dev.0
    depends_on:
      - renewer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certificates:/etc/nginx/certs:ro
    restart: always
  nexus:
    image: docker-repository-127-0-0-1.nip.io/nexus:0.2.0-dev.0
    env_file: .env
    volumes:
      - nexus-data:/nexus-data
    environment:
      VIRTUAL_HOST: nexus-127-0-0-1.nip.io
      VIRTUAL_PORT: 8081
  nexus-provision:
    image: docker-repository-127-0-0-1.nip.io/nexus-provision:0.2.0-dev.0
    env_file: .env
    depends_on:
      - nexus
    restart: "no"
  renewer:
    image: docker-repository-127-0-0-1.nip.io/step-renewer:0.2.0-dev.0
    depends_on:
      - ca
    volumes:
      - certificates:/var/local/step
    environment:
      STEP_CA_URL: https://ca
      STEP_FINGERPRINT: 84a033e84196f73bd593fad7a63e509e57fd982f02084359c4e8c5c864efc27d
      STEP_KID: CXgEGRHJPdw7K5BMxx5NbaqywXGiXFwnLisfI6uD5jw
      STEP_PROVISIONER_PASSWORD: admin123
      STEP_ROOT: /var/local/step/root_ca.crt
      STEPPATH: /home/step
  smee-client:
    image: docker-repository-127-0-0-1.nip.io/smee-client:0.1.0-dev.0
    command: "-u https://smee.io/${SMEE_ID} -t http://jenkins:8080/github-webhook/"
volumes:
  nexus-data:
  certificates:
