version: '3.9'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    stdin_open: true
    tty: true
    init: true
    ports:
      - '9229:9229'
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    environment:
      VERBOSE: ${VERBOSE}
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    stdin_open: true
    tty: true
    init: true
    ports:
      - '9229:9229'
    environment:
      VERBOSE: ${VERBOSE}
      JEST_ARGS: ${JEST_ARGS}
      WORKING_DIR: ${WORKING_DIR}/cicd/build-pipeline-generator
    working_dir: ${WORKING_DIR}/cicd/build-pipeline-generator
    volumes:
      - ${WORKSPACE_MOUNT}:${WORKSPACE_PREFIX}
  build-pipeline-generator:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-pipeline-generator
    working_dir: ${WORKING_DIR}
    volumes:
      - ${WORKSPACE_MOUNT}:${WORKSPACE_PREFIX}
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - '6969:8080'
