jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 4
jobs:
  - script: >
      multibranchPipelineJob('poc-jenkins-monorepo') {
        branchSources {
          github {
            id = 'poc-jenkins-monorepo'
            repoOwner('Nathan-Smith')
            repository('poc-jenkins-monorepo')
            scanCredentialsId('81001ac6-a96b-4423-aa2d-cb574d7c2fe7')
          }
        }
      }
security:
  scriptApproval:
    approvedSignatures:
    - "method org.jgrapht.Graph addEdge java.lang.Object java.lang.Object"
    - "method org.jgrapht.Graph addVertex java.lang.Object"
    - "method org.jgrapht.Graph outgoingEdgesOf java.lang.Object"
    - "method org.jgrapht.Graph removeVertex java.lang.Object"
    - "method org.jgrapht.Graph vertexSet"
    - "new org.jgrapht.graph.DefaultDirectedGraph java.lang.Class"
credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "GitHub Personal Access Token"
          id: "af5ca59f-7b63-43a1-9c50-90ec1ad21d39"
          scope: GLOBAL
          secret: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      - usernamePassword:
          description: "GitHub Personal Access Token"
          id: "81001ac6-a96b-4423-aa2d-cb574d7c2fe7"
          scope: GLOBAL
          password: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      - usernamePassword:
          description: "Docker Repository"
          id: "docker-repository-127-0-0-1.nip.io"
          password: "jenkins123"
          scope: GLOBAL
          username: "jenkins"
unclassified:
  gitHubPluginConfig:
    configs:
    - credentialsId: "af5ca59f-7b63-43a1-9c50-90ec1ad21d39"
      manageHooks: false
  location:
    url: "https://jenkins-127-0-0-1.nip.io/"
