version: '3.9'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /opt/app
    volumes:
      - .:/opt/app
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    working_dir: ${WORKING_DIR}/tests-web-ui
    volumes:
      - ${WORKSPACE_MOUNT}:${WORKSPACE_PREFIX}
  calculator-app:
    image: docker-repository-127-0-0-1.nip.io/calculator-app:0.1.0-dev.0
  chrome:
    image: selenium/standalone-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
